### ISSUE TITLE
Automatic Line Break is not working in gap with commands.

### ISSUE THREAD

**Issue by duichwer** [FrankMittelbach/fmitex#10]
If i use `gap` with normal text everything works fine, but if I use it with some text of a command it does not work.

Is there some way to tell latex to evaluate the text at first and perform the dotted line afterwards?
```tex
\documentclass{scrbook}
\RequirePackage[dot,teacher-mode]{dashundergaps} % Load for dotted line
 \dashundergapssetup{
   ,gap-font           = \normalfont
   ,teacher-gap-format = dot
   ,gap-widen
   ,gap-extend-minimum = 2pt
   ,gap-extend-percent = 1
 }
\newcommand{\myipsum}{At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.}
\begin{document}
  \chapter{Test}
  Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. \gap*{At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.} Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.\\
  \gap*{\myipsum}
\end{document}
```

![image](https://user-images.githubusercontent.com/16852427/74217016-818cec80-4ca6-11ea-95f7-bef9600d52ee.png)

**Comment by FrankMittelbach** [comment]
This is really a limitation of the `ulem` package commands for underlining, dashing, etc. Any command or brace group inside their argument is set in a box, see `texdoc ulem`.
So some level of limitation will always exist and I should probably document that. E.g., you get the same effect if you use, say `\emph{...}` inside the `\gap` argument.

In your case, however we can try to expand the argument first in the hope that commands vanish and get replaced by text whenever possible, e.g., something like this:
```
\ExplSyntaxOn \makeatletter
\DeclareDocumentCommand \gap { som } 
{  \protected@edef\next{#3}
   \exp_args:Nnno \__fmdug_gap:nnn {#1}{#2}{\next} }
\ExplSyntaxOff \makeatother
```
Not sure I'm going to implement it exactly like this, but you may want to stick that for now into your preamble after loading the package and experiment with it. (by the way you should not use `\RequirePackage` for loading.)

**Comment by FrankMittelbach** [comment]
New version 2.0g uploaded to CTAN
