### ISSUE TITLE
Update documentation to compare this with nowidow package

### ISSUE THREAD

**Issue by krishnakumarg1984** [FrankMittelbach/fmitex#2]
Raphael Pinson's `nowidow` package seems to provide similar functionality. 

Can you consider expanding the documentation to compare and contrast your package's functionality with `nowidow`?  For instance, 
- can both be loaded together without conflicts? 
- Is there a benefit of doing so? 
- What would be the recommended load order in that case?
-  Which engines does it work with etc.

**Comment by FrankMittelbach** [comment]
It does not provide a similar functionality. the `widows-and-orphans` package is there to "detect" problems and leave the correction to the user. There are many ways how to correct things, the most simplest way is simply to forbid them and push full lines from one page to the next. However, that is the least desirable way (except that it can be automated) as it will generate ugly empty pages).

In the upcoming TugBoat journal there will be in article discussing what other alternatives are and their pros and cons. Once that is published it will also appear on the LaTeX Project website.

Now for `nowidow`. This package offers some commands to implement that pushing of lines from one page to another in a simple way. In that respect it is implementing one of the possibilities discussed in the article  and I see no reason why the two packages should not be able to coexist, they complement each other. It  is however, in many cases not the best solution to get rid of a widow or orphan when the interest is to achive high typographical quality.

**Comment by dbitouze** [comment]
Would be nice to provide comparison between `parskip` and [`nccparskip`](https://ctan.org/pkg/nccparskip) as well.

**Comment by FrankMittelbach** [comment]
@dbitouze compared to the old `parskip` package `nccparskip` offered the possibility to set different parskip values instead of using a fixed value. In other respect it does nothing ie less than the old `parskip` package did.  As the new version can also set the skip explicitly and also fixes headings and tocs `nccparskip` is superseeded unless you want to change parskip settings in mid-document.

**Comment by dbitouze** [comment]
Thanks.

**Comment by FrankMittelbach** [comment]
added some comments to the dtx file, will show up in next release
