### ISSUE TITLE
Error compilation with dashundergaps

### ISSUE THREAD

**Issue by LH31** [FrankMittelbach/fmitex#7]
Hello
I installed your package dashundergaps but when I use \gap*{} in my text, I get this error :
```
./Activites/test.tex:72: Undefined control sequence.
\__fmdug_gap:nnn ...{totalgapnumber}\bool_xor:nnT 
                                                  {#1}{\l__fmdug_number_bool...
l.72 \item \gap*{L'eau}
                        bout à 100 °C.
? 
```

If I ignore the error message and I generate the pdf, in the text it looks like that. Any idea?
Thanks
LH

![Capture d’écran 2019-07-13 à 16 51 00](https://user-images.githubusercontent.com/52803876/61173081-895ca500-a58e-11e9-92a9-17cf8319ea01.png)

**Comment by FrankMittelbach** [comment]
Can you please provide a complete test that I can use to reproduce your problem and please include the .log file.

**Comment by LH31** [comment]
Thank you for your answer. Please find attached the log, pdf and the source file in a txt file as the .tex format is not supported by the website.
[Sans-titre.log](https://github.com/FrankMittelbach/fmitex/files/3389250/Sans-titre.log)
[Sans-titre.pdf](https://github.com/FrankMittelbach/fmitex/files/3389251/Sans-titre.pdf)
[Sans-titre.txt](https://github.com/FrankMittelbach/fmitex/files/3389252/Sans-titre.txt)

**Comment by LH31** [comment]
Thank you for your answer. Please find attached the log, pdf and the source file in a txt file as the .tex format is not supported by the website.
[Sans-titre.pdf](https://github.com/FrankMittelbach/fmitex/files/3389253/Sans-titre.pdf)
[Sans-titre.txt](https://github.com/FrankMittelbach/fmitex/files/3389254/Sans-titre.txt)
[Sans-titre.log](https://github.com/FrankMittelbach/fmitex/files/3389255/Sans-titre.log)

**Comment by FrankMittelbach** [comment]
your log shows
```
(/usr/local/texlive/2017/texmf-dist/...
```
In other words you have manually (?) installed the package on top of a 2017 distribution.
However, it uses expl3 and needs that at least in the TL 2018 version. You can try to also locally update just the expl3 packages but I strongly recommend against it. Better update your TL distribution, there are so many updates worth having and the manual update of expl3 may pose other problems.

**Comment by LH31** [comment]
Hi, I updated Texlive to the 2019 version and it solved the problem, thanks a lot for your help!

**Comment by FrankMittelbach** [comment]
ok, good. I keep it open to remind me to put in a check for an old expl3 version (maybe).
