### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by pasbi** [FrankMittelbach/fmitex#9]
It would be nice if the Readme would list the commands provided by `dashundergaps` package and briefly explains what they do and how to use them.

**Comment by FrankMittelbach** [comment]
Duplicating information isn't really a good idea; it is bound to go stale. All LaTeX packages have documentation when installed  simply by saying
```
texdoc <package-name>
```
And of course that is also in the sources here as .dtx and .tex files

That doc is also displayed on CTAN, ie https://ctan.org/pkg/dashundergaps

**Comment by pasbi** [comment]
I didn't see the pdf document at CTAN ... thanks :+1:
